version: "3"
services:
  nginx:
    image: brmasis/compratec:gateway
    entrypoint: nginx
    ports:
        - 8888:80
    command: ["-g", "daemon off;", "-c", "/etc/nginx/conf.d/default.conf"]
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
        - orders
        - visualizer
        - users
        - catalog
  users:
    image: brmasis/compratec:users-service
    ports:
      - "3002:2000"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
  catalog:
    image: brmasis/compratec:catalog-service
    ports:
      - "3008:5000"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
    depends_on:
        - rs
  orders:
    image: brmasis/compratec:orders-service
    ports:
      - "3006:3000"
      - "5432:5432"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
  rs1:
    image: mongo:3.4
    command: mongod --replSet "rs0"

  rs2:
    image: mongo:3.4
    command: mongod --replSet "rs0"

  rs3:
    image: mongo:3.4
    command: mongod --replSet "rs0"

  rs:
    image: brmasis/compratec:mongodb
    ports:
      - "27017:27017"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10

  visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "3005:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]
